### ISSUE TITLE
Export error: No such file or directory

### ISSUE THREAD

**Issue by alexander-myltsev** [KnugiHK/WhatsApp-Key-DB-Extractor#4]
The script doesn't extract files to `extracted` folder. The log:

```
bash WhatsAppKeyDBExtract.sh

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================


Please connect your Android device with USB Debugging enabled:

cannot connect to daemon at tcp:5037: Connection refused
* daemon not running; starting now at tcp:5037
* daemon started successfully

Found legacy WhatsApp 2.11.431 in local folder

WhatsApp 2.22.24.78 installed

Backing up WhatsApp 2.22.24.78
/data/app/~~zAdYkJWppPgDU9zErKPnoA==/com.whatsapp-rlwiVCEsQG9rkp3AHsahjQ==/base.apk: 1 file pulled, 0 skipped. 35.2 MB/s (42137757 bytes in 1.143s)
Backup complete

Removing WhatsApp 2.22.24.78 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
Performing Streamed Install
adb: failed to install tmp/LegacyWhatsApp.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1609508919.tmp/base.apk: Failed to load asset path /data/app/vmdl1609508919.tmp/base.apk]
Install complete

WARNING: adb backup is deprecated and may be removed in a future release
Now unlock your device and confirm the backup operation...

Please enter your backup password (leave blank for none) and press Enter:

tar: apps/com.whatsapp/f/key: Not found in archive
tar: Error exit delayed from previous errors.
tar: apps/com.whatsapp/f/encrypted_backup.key: Not found in archive
tar: Error exit delayed from previous errors.
tar: apps/com.whatsapp/db/msgstore.db: Not found in archive
tar: Error exit delayed from previous errors.
tar: apps/com.whatsapp/db/wa.db: Not found in archive
tar: Error exit delayed from previous errors.
tar: apps/com.whatsapp/db/axolotl.db: Not found in archive
tar: Error exit delayed from previous errors.
tar: apps/com.whatsapp/db/chatsettings.db: Not found in archive
tar: Error exit delayed from previous errors.
tar: apps/com.whatsapp/Avatars: Not found in archive
tar: Error exit delayed from previous errors.

Saving whatsapp.cryptkey ...
cp: tmp/apps/com.whatsapp/f/key: No such file or directory

Saving encrypted_backup.key ...
cp: tmp/apps/com.whatsapp/f/encrypted_backup.key: No such file or directory
Saving msgstore.db ...
cp: tmp/apps/com.whatsapp/db/msgstore.db: No such file or directory
Saving wa.db ...
cp: tmp/apps/com.whatsapp/db/wa.db: No such file or directory
Saving axolotl.db ...
cp: tmp/apps/com.whatsapp/db/axolotl.db: No such file or directory
Saving chatsettings.db ...
cp: tmp/apps/com.whatsapp/Avatars: No such file or directory
Saving Avatars...
cp: tmp/apps/com.whatsapp/db/chatsettings.db: No such file or directory

Pushing cipher key to: /sdcard/WhatsApp/Databases/.nomedia
adb: error: cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory

Restoring WhatsApp 2.22.24.78
Performing Streamed Install
Success
Restore complete

Cleaning up temporary files ...
Done

Operation complete

Please press Enter to quit...
```

OS: macOS Monterey 12.6
Android version: 13

**Comment by formalist** [comment]
Same error, tried  WhatsAppKeyDBExtract.bat and WhatsAppKeyDBExtract.ps1

OS: Windows 10
Android version: 13 (LineageOS)

**Comment by KnugiHK** [comment]
Notice the quoted line, which means the legacy WhatsApp is not installed, hence, nothing is extracted.
> adb: failed to install tmp/LegacyWhatsApp.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1609508919.tmp/base.apk: Failed to load asset path /data/app/vmdl1609508919.tmp/base.apk]

~~I also notice your Android version is 13, which, I guess, may be the root cause of the problem. I will do some tests on it.~~

EDIT: The problem could also be caused by the fact that https://whatcrypt.com/WhatsApp-2.11.431.apk is no longer available. If this is the case, you may try to download the APK from the [mentioned links in README file](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor#caution) or the same APK from [Web Archive](https://web.archive.org/web/20220111155623/https://whatcrypt.com/WhatsApp-2.11.431.apk).

**Comment by zzombocom** [comment]
I've also seen the same, without the error for installing the legacy version.

Android version 10
Ubuntu 20.04.6

```
$ ./WhatsAppKeyDBExtract.sh 

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================


Please connect your Android device with USB Debugging enabled:

cannot connect to daemon at tcp:5037: Address family not supported by protocol
* daemon not running; starting now at tcp:5037
* daemon started successfully

Downloading legacy WhatsApp 2.11.431 to local folder

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.4M  100 17.4M    0     0  5938k      0  0:00:03  0:00:03 --:--:-- 5938k

WhatsApp 2.23.6.76 installed

Backing up WhatsApp 2.23.6.76
/data/app/com.whatsapp-fzI_2AJbv2iVfzxIa9XWXQ==/base.apk: 1 file pulled. 25.4 MB/s (43260070 bytes in 1.625s)
Backup complete

Removing WhatsApp 2.23.6.76 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
Success
Install complete

Now unlock your device and confirm the backup operation...

Please enter your backup password (leave blank for none) and press Enter: 

tar: apps/com.whatsapp/f/key: Not found in archive
tar: Exiting with failure status due to previous errors
tar: apps/com.whatsapp/f/encrypted_backup.key: Not found in archive
tar: Exiting with failure status due to previous errors
tar: apps/com.whatsapp/db/msgstore.db: Not found in archive
tar: Exiting with failure status due to previous errors
tar: apps/com.whatsapp/db/wa.db: Not found in archive
tar: Exiting with failure status due to previous errors
tar: apps/com.whatsapp/db/axolotl.db: Not found in archive
tar: Exiting with failure status due to previous errors
tar: apps/com.whatsapp/db/chatsettings.db: Not found in archive
tar: Exiting with failure status due to previous errors
tar: apps/com.whatsapp/Avatars: Not found in archive
tar: Exiting with failure status due to previous errors

Saving whatsapp.cryptkey ...
cp: cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory

Saving encrypted_backup.key ...
cp: cannot stat 'tmp/apps/com.whatsapp/f/encrypted_backup.key': No such file or directory
Saving msgstore.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/msgstore.db': No such file or directory
Saving wa.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/wa.db': No such file or directory
Saving axolotl.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/axolotl.db': No such file or directory
Saving chatsettings.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/Avatars': No such file or directory
Saving Avatars...
cp: cannot stat 'tmp/apps/com.whatsapp/db/chatsettings.db': No such file or directory

Pushing cipher key to: /sdcard/WhatsApp/Databases/.nomedia
adb: error: cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory

Restoring WhatsApp 2.23.6.76
Success
Restore complete

Cleaning up temporary files ...
Done

Operation complete

Please press Enter to quit...

```

**Comment by gekigek99** [comment]
Had the same problem, solved with:
- downloading [this version of whatsapp (from the instructions)](https://web.archive.org/web/20141111030303if_/http://www.whatsapp.com/android/current/WhatsApp.apk)
- renaming to `LegacyWhatsApp.apk`
- moving it into tmp folder
- (then I allowed on my phone the "update")

**Comment by KnugiHK** [comment]
> Had the same problem, solved with:
> 
>     * downloading [this version of whatsapp (from the instructions)](https://web.archive.org/web/20141111030303if_/http://www.whatsapp.com/android/current/WhatsApp.apk)
> 
>     * renaming to `LegacyWhatsApp.apk`
> 
>     * moving it into tmp folder
> 
>     * (then I allowed on my phone the "update")

I updated the source of the APK and forgot to put an update here. Could you verify that the script from the master branch works without any manual steps?

**Comment by gekigek99** [comment]
sorry for the delay I got caught up in life...

still not working:

full log
```ps
PS C:\Users\gekigek99\WhatsApp-Key-DB-Extractor> .\WhatsAppKeyDBExtract.ps1

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v5.1 (22/02/2022)          ###          =
=========================================================================

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

WhatsApp 2.23.7.78 installed

Downloading legacy WhatsApp 2.11.431 to local folder

curl: (1) Protocol "https" not supported or disabled in libcurl

Backing up WhatsApp 2.23.7.78
4999 KB/s (49224281 bytes in 9.614s)
Backup complete

Removing WhatsApp 2.23.7.78 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
Invalid APK file: tmp\LegacyWhatsApp.apk
Install complete

Now unlock your device and confirm the backup operation.

*clik on backup data on phone*

Please enter your backup password (leave blank for none) and press Enter:

Invlaid Magic:
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid Magic
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:516)
        at org.nick.abe.Main.main(Main.java:142)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 2 more
Caused by: java.lang.IllegalArgumentException: Invalid Magic
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:337)
        ... 4 more

C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\gekigek99\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...
Done

Restoring WhatsApp 2.23.7.78
3916 KB/s (49224281 bytes in 12.272s)
Success
Restore complete

Removing WhatsApp 2.23.7.78 temporary apk


Operation complete

Premere un tasto per continuare . . .
PS C:\Users\gekigek99\WhatsApp-Key-DB-Extractor>
```

---

I think that once the script fails to download the legacy executable or legacy executable is invalid, it should just exit and report the command that failed. (otherwise people see the java error and followings snowballing which distracts from the real issue that is a curl fail)

**Comment by KnugiHK** [comment]
I updated the curl binary for Windows in 9a7e246. It should fix the problem? I guess.

As for @gekigek99's suggestion regarding exit when failing, I implemented it in my development environment. But given the new law of Hong Kong regarding SIM card registration, I currently don't have a testing environment for me to test my changes. Once it is tested, I will commit that.

**Comment by AdMediastic** [comment]
For me this error is coming up:
```

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v5.1 (22/02/2022)          ###          =
=========================================================================

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

WhatsApp 2.23.12.78 installed

Found legacy WhatsApp 2.11.431 in local folder

Backing up WhatsApp 2.23.12.78
2014 KB/s (50171085 bytes in 24.322s)
Backup complete

Removing WhatsApp 2.23.12.78 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
3445 KB/s (18329558 bytes in 5.194s)
Success
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter:


D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Unexpected EOF on archive file
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Unexpected EOF on archive file
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Unexpected EOF on archive file
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Unexpected EOF on archive file
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Unexpected EOF on archive file
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Unexpected EOF on archive file
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Unexpected EOF on archive file
D:\Hacking\Sharing\WhatsApp-Key-DB-Extractor\bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...
Done

Restoring WhatsApp 2.23.12.78
1648 KB/s (50171085 bytes in 29.727s)
Success
Restore complete

Removing WhatsApp 2.23.12.78 temporary apk


Operation complete
```

Earlier I was getting the same error as you guys, I then replaced the `LegacyWhatsApp.apk` to the version which is mentioned by @gekigek99 

Let me if anyone is able to remediate this issue!

**Comment by KnugiHK** [comment]
@AdMediastic I notice this from your log
> Found legacy WhatsApp 2.11.431 in local folder

Where did you get the APK file, and can you check if it is an old version APK?

Also, please make sure the password to the backup is correct.

**Comment by AdMediastic** [comment]
> @AdMediastic I notice this from your log
> 
> > Found legacy WhatsApp 2.11.431 in local folder
> 
> Where did you get the APK file, and can you check if it is an old version APK?
> 
> Also, please make sure the password to the backup is correct.

Hey @KnugiHK 

I have downloaded the WhatsApp APK which was mentioned by @gekigek99 in his comment. 
It worked perfectly for me. 

Let me know if you if I can help in anyway?

**Comment by KnugiHK** [comment]
> > @AdMediastic I notice this from your log
> > > Found legacy WhatsApp 2.11.431 in local folder
> > 
> > 
> > Where did you get the APK file, and can you check if it is an old version APK?
> > Also, please make sure the password to the backup is correct.
> 
> Hey @KnugiHK
> 
> I have downloaded the WhatsApp APK which was mentioned by @gekigek99 in his comment. It worked perfectly for me.
> 
> Let me know if you if I can help in anyway?

The APK mentioned should be the same file downloaded by the script. Could you compare the checksum of the manually downloaded APK and the APK downloaded by the script?

**Comment by daanlenaerts** [comment]
I am getting the same errors. I tried playing around with the backup file a bit and it seems there's no com.whatsapp directory in there at all. Do you know what could be wrong @KnugiHK?

**Comment by KnugiHK** [comment]
> I am getting the same errors. I tried playing around with the backup file a bit and it seems there's no com.whatsapp directory in there at all. Do you know what could be wrong @KnugiHK?

Hi. What OS are you using?

**Comment by daanlenaerts** [comment]
Hi, I've tried on Windows and macOS, but hit the same issue. Everything seems to work fine (old Whatsapp version download, install, backup is started, existing Whatsapp is restored) there just doesn't seem to be anything about Whatsapp in the backup.

________________________________

**Comment by KnugiHK** [comment]
> Hi, I've tried on Windows and macOS, but hit the same issue. Everything seems to work fine (old Whatsapp version download, install, backup is started, existing Whatsapp is restored) there just doesn't seem to be anything about Whatsapp in the backup.

I tried it on Windows and Linux. It works fine in Windows but not in Linux. Not sure if it is the problem of ADB. It will need further investigation.
Meanwhile, you may try to do it manually by following the script's commands.

**Comment by SavSanta** [comment]
I had the similar issue I was semi-able to get around some of the issues by  modifying the script. Im about to go to work where I wont have my phone for 10hrs to continue testing and seeing how to possibly identify and patch/solution but would like to know if this output would be sufficient to do a WA backup?

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true                                                
apps/com.whatsapp/f/key                                                                                                      
tar: apps/com.whatsapp/f/encrypted_backup.key: Not found in archive                                                          
tar: Exiting with failure status due to previous errors                                                                      
apps/com.whatsapp/db/msgstore.db                                                                                             
apps/com.whatsapp/db/wa.db                                                                                                   
apps/com.whatsapp/db/axolotl.db                                                                                              
apps/com.whatsapp/db/chatsettings.db                                                                                         
tar: apps/com.whatsapp/Avatars: Not found in archive                                                                         
tar: Exiting with failure status due to previous errors  
```
Note the first tar error


Android 10. No Google Backup or associate Google Backup Account on Device btw

**Comment by SavSanta** [comment]
Back and came to attempt to complete where I left off this morning. 
I wasnt getting a key with the current version even using Legacy app. The changes I made was to add a pause to the script after the installation of the Legacy version. (To do this add the lines `echo -e "\nPaused. Check the Whatsapp on the device version. Then press Enter: "; read trashvar` to the Linux/Mac shellscript.)

After when Im prompted by my added line. I manually opened the WA application on my mobile device.
You'll be greeted with a permissions page. You accept the permissions then exit the WA application.

After that  as the script proceeds I successfully get

```
apps/com.whatsapp/f/key                                                                                                      
tar: apps/com.whatsapp/f/encrypted_backup.key: Not found in archive                                                          
tar: Exiting with failure status due to previous errors                                                                      
apps/com.whatsapp/db/msgstore.db                                                                                             
apps/com.whatsapp/db/wa.db                                                                                                   
apps/com.whatsapp/db/axolotl.db                                                                                              
apps/com.whatsapp/db/chatsettings.db                                                                                         
tar: apps/com.whatsapp/Avatars: Not found in archive                                                                         
tar: Exiting with failure status due to previous errors                                                                      
                                                                                                                             
Saving whatsapp.cryptkey ...                                                                                                 
                                                                                                                             
Saving encrypted_backup.key ...                                                                                              
cp: cannot stat 'tmp/apps/com.whatsapp/f/encrypted_backup.key': No such file or directory                                    
Saving msgstore.db ...                                                                                                       
Saving wa.db ...                                                                                                             
Saving axolotl.db ...                                                                                                        
Saving chatsettings.db ...                                                                                                   
cp: cannot stat 'tmp/apps/com.whatsapp/Avatars': No such file or directory                                                   
Saving Avatars...                                                                                                            
                                                                                                                             
Pushing cipher key to: /sdcard/WhatsApp/Databases/.nomedia                                                                   
tmp/apps/com.whatsapp/f/key: 1 file pushed, 0 skipped. 0.0 MB/s (158 bytes in 0.069s)                                        
                                                                                                                             
Restoring WhatsApp 2.23.19.5                                                                                                 
Performing Streamed Install                                                                                                  
Success                                                                                                                      
Restore complete                                                                                                             
                                                                                                                             
Cleaning up temporary files ...                                                                                              
Done                                                                                                                         
                                                                                                                             
Operation complete                                                                                                           
                                                                                                                             
Please press Enter to quit... 
```


**BUT**

There is another problem. When trying to use the key in the companion WA-Exporter I get an error that basically states
```
Decryption key specified, decrypting WhatsApp backup...
t1  KEYFILE byteslice 30-62 is:           bb7cb3bbe1101b2c3c944ea3f40ea7b07ee2b723ab2c7c7bbb3bd4dc0b522d445
t2 DATABASE byteslice 15-47 is:           dab83da1a304037bb9bab78492e8bcbb4bf7b48cbdfcb831778b4489ebe74ecb2
Traceback (most recent call last):
<snip>
    raise ValueError("The signature of key file and backup file mismatch")
ValueError: The signature of key file and backup file mismatch
```

So in my case the key doesnt work. On the road again to playing around some more

OS: Android 10 
WA ver: 2.23.19.5

**Comment by SavSanta** [comment]
Upon further review. The key was that was obtained after granting requested permissions and launching WA is correct.

My issue was understanding Androids storage/saving locations ever since KitKat. They showed up last nites. I had WA backups under `/storage/0000-0007/WhatsApp/Databases/ ` from May of this year, which is the first time I installed the WA  ever on this phone but I updated WA about 2 weeks ago. After making backup and digging trying to navigate Android's weird storage, I ejected my physical microSD card to narrow the search focus/possible save locations, and I found the actual path in my case now is in the (badly named) `/sdcard/Android/media/com.whatsapp/Databases/` in my case. Dont know why theyre different. Though one more thing for others to note for others here

PR incoming

**Comment by KnugiHK** [comment]
@SavSanta Really appreciate your persistence in finding the issue. I will check out your PR later.

**Comment by SavSanta** [comment]
@KnugiHK Aint no thang. I've got to thank you more as Im glad this worked exceptionally to backup my database. I also intend to open a PR though for the documentation btw. As some of it can be cleared. Thanks again

**Comment by KnugiHK** [comment]
Hi everyone. Thanks to @SavSanta, the issue should be fixed now. Feel free to try the latest scripts and remember to follow the latest instructions. If the fix can be confirmed, I will release a new version.

**Comment by SavSanta** [comment]
@KnugiHK Right on! Im currently away from.dev computer for a while....but i think i have ADB on my netbook. Ill try and give it ago. Thx

**Comment by getused2me** [comment]
EDIT: i think my issue is different but i solved the issue by first manually placing the apk to the tmp folder and then allowing "install via usb" in phone on developer options. thanks

> Hi everyone. Thanks to @SavSanta, the issue should be fixed now. Feel free to try the latest scripts and remember to follow the latest instructions. If the fix can be confirmed, I will release a new version.

edit: i manually downloaded the apk from the archive link but it still doesn't work. it says user cancelled.

i still have the issue. windows 10. xiaomi note 8 pro. android version 11

these are the files in the tmp folder when cmd is like this:

![image](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/assets/61414675/64241154-5674-4dea-8516-326325c6eb5c)
![image](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/assets/61414675/33f8eabc-956f-4f98-88cb-f4619651b947)

and this is cmd after i enter password. i need to manually download and install whatsapp from play store after everything is done. any help would be greatly appreciated.

![image](https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor/assets/61414675/4da7aa3e-1d2e-487f-8627-0d704f88af6d)

**Comment by Heeere-GittyGitty** [comment]
Still not working on latest Galaxy S22.


> EDIT: i think my issue is different but i solved the issue by first manually placing the apk to the tmp folder and then allowing "install via usb" in phone on developer options. thanks
> 
> > Hi everyone. Thanks to @SavSanta, the issue should be fixed now. Feel free to try the latest scripts and remember to follow the latest instructions. If the fix can be confirmed, I will release a new version.
> 
> edit: i manually downloaded the apk from the archive link but it still doesn't work. it says user cancelled.
> 
> i still have the issue. windows 10. xiaomi note 8 pro. android version 11
> 
> these are the files in the tmp folder when cmd is like this:
> 
> ![image](https://private-user-images.githubusercontent.com/61414675/303775972-64241154-5674-4dea-8516-326325c6eb5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDQyMzMsIm5iZiI6MTcxMzgwMzkzMywicGF0aCI6Ii82MTQxNDY3NS8zMDM3NzU5NzItNjQyNDExNTQtNTY3NC00ZGVhLTg1MTYtMzI2MzI1YzZlYjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YzY5OWE4NjQ4ZjdjZDVhNzM4ZTUyNDMyODkyYjM4ZjI1ZjEwMzM3ZTcyNjQ4ZWIzZWE4ZTNkOGJhZTAzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJkqnHWNNcSEkzpbroC88Fqaep_7v7TtLJ1BYlLC1GA) ![image](https://private-user-images.githubusercontent.com/61414675/303775987-33f8eabc-956f-4f98-88cb-f4619651b947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDQyMzMsIm5iZiI6MTcxMzgwMzkzMywicGF0aCI6Ii82MTQxNDY3NS8zMDM3NzU5ODctMzNmOGVhYmMtOTU2Zi00Zjk4LTg4Y2ItZjQ2MTk2NTFiOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNTBiNWJjYTQ4NTJhMjg3NTUxOWU5MTZjYmE3Njg1N2ZmMTI0YjI2NDcwZjAxZjFmZWQwOWNkNjEzMWYxMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cdb9OLrlvNLU-GWVT4Wp0sn5cxV6g9dDKhLvGZfMjiA)
> 
> and this is cmd after i enter password. i need to manually download and install whatsapp from play store after everything is done. any help would be greatly appreciated.
> 
> ![image](https://private-user-images.githubusercontent.com/61414675/303776320-4da7aa3e-1d2e-487f-8627-0d704f88af6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDQyMzMsIm5iZiI6MTcxMzgwMzkzMywicGF0aCI6Ii82MTQxNDY3NS8zMDM3NzYzMjAtNGRhN2FhM2UtMWQyZS00ODdmLTg2MjctMGQ3MDRmODhhZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDBmYjAyZDcxOWJlZGU1NmEyMzQyZTI1NmY0ZTk0MWZjODRmNDJkYzdhY2Q0ZTQyNDNiMTVkOTc0ZWU3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYfcUHPn02D-k9AkAUO-yvAjJtiRI74LU-KKcdgNcBQ)

Exactly the same issue on S22 with latest android.

I put the legacywhatsapp apk and installed manually because of ADB showing downgrade errors, but running the second part of the script always has this behaviour as seen above.

Ideas?

**Comment by KnugiHK** [comment]
> Still not working on latest Galaxy S22.
> 
> > EDIT: i think my issue is different but i solved the issue by first manually placing the apk to the tmp folder and then allowing "install via usb" in phone on developer options. thanks
> > > Hi everyone. Thanks to @SavSanta, the issue should be fixed now. Feel free to try the latest scripts and remember to follow the latest instructions. If the fix can be confirmed, I will release a new version.
> > 
> > 
> > edit: i manually downloaded the apk from the archive link but it still doesn't work. it says user cancelled.
> > i still have the issue. windows 10. xiaomi note 8 pro. android version 11
> > these are the files in the tmp folder when cmd is like this:
> > ![image](https://private-user-images.githubusercontent.com/61414675/303775972-64241154-5674-4dea-8516-326325c6eb5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDQyMzMsIm5iZiI6MTcxMzgwMzkzMywicGF0aCI6Ii82MTQxNDY3NS8zMDM3NzU5NzItNjQyNDExNTQtNTY3NC00ZGVhLTg1MTYtMzI2MzI1YzZlYjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YzY5OWE4NjQ4ZjdjZDVhNzM4ZTUyNDMyODkyYjM4ZjI1ZjEwMzM3ZTcyNjQ4ZWIzZWE4ZTNkOGJhZTAzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJkqnHWNNcSEkzpbroC88Fqaep_7v7TtLJ1BYlLC1GA) ![image](https://private-user-images.githubusercontent.com/61414675/303775987-33f8eabc-956f-4f98-88cb-f4619651b947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDQyMzMsIm5iZiI6MTcxMzgwMzkzMywicGF0aCI6Ii82MTQxNDY3NS8zMDM3NzU5ODctMzNmOGVhYmMtOTU2Zi00Zjk4LTg4Y2ItZjQ2MTk2NTFiOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNTBiNWJjYTQ4NTJhMjg3NTUxOWU5MTZjYmE3Njg1N2ZmMTI0YjI2NDcwZjAxZjFmZWQwOWNkNjEzMWYxMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cdb9OLrlvNLU-GWVT4Wp0sn5cxV6g9dDKhLvGZfMjiA)
> > and this is cmd after i enter password. i need to manually download and install whatsapp from play store after everything is done. any help would be greatly appreciated.
> > ![image](https://private-user-images.githubusercontent.com/61414675/303776320-4da7aa3e-1d2e-487f-8627-0d704f88af6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDQyMzMsIm5iZiI6MTcxMzgwMzkzMywicGF0aCI6Ii82MTQxNDY3NS8zMDM3NzYzMjAtNGRhN2FhM2UtMWQyZS00ODdmLTg2MjctMGQ3MDRmODhhZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDBmYjAyZDcxOWJlZGU1NmEyMzQyZTI1NmY0ZTk0MWZjODRmNDJkYzdhY2Q0ZTQyNDNiMTVkOTc0ZWU3MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYfcUHPn02D-k9AkAUO-yvAjJtiRI74LU-KKcdgNcBQ)
> 
> Exactly the same issue on S22 with latest android.
> 
> I put the legacywhatsapp apk and installed manually because of ADB showing downgrade errors, but running the second part of the script always has this behaviour as seen above.
> 
> Ideas?

The nearest one I can possibly get is S21. I will try to reproduce it when I have the phone.

**Comment by Heeere-GittyGitty** [comment]
It's basically similar on any samsung updated to latest version. I don't
know 100% the details on how your code works, but even if I install the old
whatsapp manually, the new screen with the option to backup and enter a
password pops up, then i choose "do backup", and put no password in the
command line.
After that I get those TAR errors of missing files.
Cumprimentos/Regards,
Artur Martins 962553178
